tools = """
[
  {
    type: 'function',
    function: {
      name: 'calculate',
      description: 'Evaluate a mathematical expression',
      parameters: {
        type: 'object',
        properties: {
          expression: {
            type: 'string',
            description: 'The mathematical expression to evaluate',
          }
        },
        required: ['expression']
      },
    },
  }
]
"""

[[messages]]
role = "system"
content = """
Your are a helpful assistant.
"""

[[messages]]
role = "user"
content = "1 + 1"
